# Generated by Django 3.1.5 on 2021-06-02 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0002_domain'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Domain',
            new_name='Domains',
        ),
        migrations.RenameField(
            model_name='domains',
            old_name='subdoamin',
            new_name='sudomain',
        ),
    ]
